# Use official Tomcat image with JDK 17
FROM tomcat:9-jdk17

# Optional: Remove default webapps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy built WAR file from Maven build
COPY target/*.war /usr/local/tomcat/webapps/ROOT.war

# Expose port 8080
EXPOSE 8090

# Start Tomcat
CMD ["catalina.sh", "run"]
