apiVersion: v1
kind: Service
metadata:
  name: maven-web-service
spec:
  type: NodePort
  selector:
    app: maven-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30090  # NodePort must be between 30000-32767
