apiVersion: v1
kind: Service
metadata:
  name: maven-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: maven-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
      name: http
    - protocol: TCP
      port: 8090
      targetPort: 8090
      name: app
